### ISSUE TITLE
UIWebView deprecated

### ISSUE THREAD

**Issue by kkarunakaran** [SuperAwesomeLTD/sa-mobile-sdk-ios#44]
UIWebView has been deprecated by iOS we are receiving the below warning form Apple when SuperAwesome is added to our app

@devgabrielcoman 

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more informat.

SA SDK still have references to UIWebView. 

<img width="724" alt="Screen Shot 2020-01-09 at 6 30 23 PM" src="https://user-images.githubusercontent.com/57362013/72113362-39c51f00-330e-11ea-8a27-9b1352907fc6.png">

**Comment by kkarunakaran** [comment]
Hello could someone give an update on this please? Also when can we expect a fix

**Comment by kkarunakaran** [comment]
We removed moat library from SuperAwesome to suppress Apple's warning

**Comment by kkarunakaran** [comment]
@devgabrielcoman  do you know when UIWebView warning might be fixed. Thanks

**Comment by gunhansancar** [comment]
Hi @kkarunakaran It is fixed in #48 and will be released in a new version this week.

**Comment by kkarunakaran** [comment]
Thanks

> Hi @kkarunakaran It is fixed in #48 and will be released in a new version this week.

Thanks a lot for the response. Just wanted to confirm if the following files are fixed as well. Since they have reference to UIWebView as well.

https://github.com/SuperAwesomeLTD/sa-mobile-sdk-ios/tree/master/Pod/Libraries

**Comment by gunhansancar** [comment]
Thanks @kkarunakaran for pointing out. 
I will contact with `moat` about the issue.
Since this is an ongoing issue maybe they have a solution already in place.

**Comment by gunhansancar** [comment]
@kkarunakaran In our SDK we use Moat version `3.6.1` and they told us they removed all the `UIWebView` references in their `3.7.5` version. So once I receive the latest version of moat, I'll update the SDK and publish a new version.

**Comment by gunhansancar** [comment]
@kkarunakaran we released a new version `7.2.5` which removes every reference to `UIWebView`. At the same time we made the `Moat` integration optional because they informed us that the version without `UIWebView` will be available in the next weeks. Thus, it is better to give you option to choose.

If you want to have the core SDK use below (without Moat, no UIWebView reference):
`pod 'SuperAwesome'`

If you want to include `Moat` integration use below:
`pod 'SuperAwesome/Moat'`

Once the `Moat` removes `UIWebView` references in their SDK and release a new version, then we will also update it and release another version.

I'll close this issue. Feel free to reopen if you encounter any problems.
